spring:
  profiles:
    default: local
  kafka:
    consumer:
      bootstrap-servers: ${my-kafka.bootstrap-servers}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"
  config:
    import:
      - 'classpath:application-mongodb.yml'
---
server.port: 8183
spring.config.activate.on-profile: local

my-kafka:
  bootstrap-servers: localhost:19092, localhost:29092, localhost:39092
---
spring.config.activate.on-profile: dev

my-kafka:
  bootstrap-servers: dev-kafka.yellowsunn.com:9092
