spring:
  datasource:
    url: jdbc:mysql://localhost:3306/simpleforum?autoReconnect=true&useSSL=false&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

server:
  error:
    include-stacktrace: never
    include-binding-errors: never
    include-message: always

logging.level:
  org.hibernate:
    SQL: debug
#    type: trace


file.dir: /file/
allow.origin: https://yellowsunn.com
