spring:
  profiles:
    default: local
  config:
    import:
      - 'classpath:application-user-infra-persistence.yml'
      - 'classpath:application-user-core.yml'
      - 'classpath:application-s3.yml'
