spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2/dbfiles/forum
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

server:
  error:
    include-stacktrace: never
    include-binding-errors: never

logging.level:
  org.hibernate:
    SQL: debug
    type: trace

file.dir: /Users/yellowsunn/Desktop/file/
