spring:
  profiles:
    default: local
  kafka:
    consumer:
      bootstrap-servers: ${my-kafka.bootstrap-servers}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"
  config:
    import:
      - 'classpath:application-persistence.yml'
      - 'classpath:application-mongodb.yml'
  cloud:
    config:
      enabled: false
---
server.port: 8181
spring.config.activate.on-profile: local

my-kafka:
  bootstrap-servers: localhost:19092, localhost:29092, localhost:39092
---
spring:
  config:
    activate:
      on-profile: dev
    import:
      - optional:configserver:http://172.16.90.6
  cloud:
    config:
      enabled: true
      profile: dev
      name: mysql, mongodb

my-kafka:
  bootstrap-servers: dev-kafka.yellowsunn.com:9092
