spring:
  profiles:
    default: local
  config:
    import:
      - 'classpath:application-persistence.yml'
      - 'classpath:application-http.yml'
      - 'classpath:application-kafka-producer.yml'
---
server:
  port: 8081
spring:
  profiles:
    active: local
