spring:
  profiles:
    default: local
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test_user_db
  h2:
    console:
      enabled: true
