spring:
  profiles:
    default: local
  batch:
    job:
      name: ${job.name:NONE}
      enabled: false
  config:
    import:
      - 'classpath:application-persistence.yml'
      - 'classpath:application-kafka-producer.yml'
      - 'classpath:application-redis.yml'
  cloud:
    config:
      enabled: false
---
server.port: 8281
spring.config.activate.on-profile: local

---
spring:
  config:
    activate:
      on-profile: dev
    import:
      - optional:configserver:http://172.16.90.6
  cloud:
    config:
      enabled: true
      profile: dev
      name: mysql, redis
