spring:
  profiles:
    default: local
  config:
    import:
      - 'classpath:application-persistence.yml'
      - 'classpath:application-http.yml'
      - 'classpath:application-kafka-producer.yml'
      - 'classpath:application-mongodb.yml'
      - 'classpath:application-redis.yml'
---
server.port: 8281
spring.config.activate.on-profile: local

