spring:
  profiles:
    default: local
---
server.port: 8281
spring.config.activate.on-profile: local
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/boards
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
---
spring.config.activate.on-profile: dev
spring:
  datasource:
    url: jdbc:mysql://192.168.29.15:3306/boards
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
