spring:
  profiles:
    default: local
  batch:
    job:
      name: ${job.name:NONE}
      enabled: false
  config:
    import:
      - 'classpath:application-persistence.yml'
      - 'classpath:application-kafka-producer.yml'
      - 'classpath:application-redis.yml'
---
server.port: 8281
spring.config.activate.on-profile: local
