spring:
  profiles:
    default: local
  kafka:
    consumer:
      bootstrap-servers: ${my-kafka.bootstrap-servers}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
  config:
    import:
      - 'classpath:application-http.yml'
      - 'classpath:application-persistence.yml'
      - 'classpath:application-mongodb.yml'
      - 'classpath:application-redis.yml'
---
server:
  port: 8181
spring:
  profiles:
    active: local

my-kafka:
  bootstrap-servers: localhost:19092, localhost:29092, localhost:39092
