server.port: 8080
spring.profiles.default: local
cloud:
  aws:
    stack:
      auto: false
    region:
      static: ap-northeast-2
      auto: false
    credentials:
      access-key: ${aws-access-key}
      secret-key: ${aws-secret-key}
---
server.port: 8082
spring.config.activate.on-profile: local
cloud:
  aws:
    s3:
      bucket: simpleboard-dev

image-base-url: http://localhost:8000
---
spring.config.activate.on-profile: dev
cloud:
  aws:
    s3:
      bucket: simpleboard-dev

image-base-url: http://api.simpleforum.yellowsunn.com
