= 유저 서비스
:toc: left

== API 목록
=== 이메일 회원가입 API
operation::post-email-signup[]

'''
=== OAuth2 로그인 혹은 회원가입 요청 API (로그인)
operation::post-oauth2-login[]

'''
=== OAuth2 로그인 혹은 회원가입 요청 API (회원가입 요청)
operation::post-oauth2-signup-request[]

'''
=== OAuth2 추가 회원 정보 입력 및 회원가입 완료 API
operation::post-oauth2-signup-complete[]

'''
=== OAuth2 계정 연동 API
operation::put-link-oauth2[]

'''
=== OAuth2 계정 연동 해제 API
operation::delete-link-oauth2[]

'''
=== 로그인 토큰 갱신 API
operation::post-refresh-user-token[]

'''
=== 회원 정보 조회 API
operation::get-users-me[]

'''
=== 회원 정보 수정 API
operation::put-users-me[]

'''
=== 회원 썸네일 이미지 수정 API
operation::patch-users-me-thumbnail[]

'''
=== 회원 탈퇴 API
operation::delete-users-me[]

'''
=== 회원 정보 조회 API (내부용)
operation::get-internal-users-by-userId[]

'''
=== 회원 정보 목록 조회 API (내부용)
operation::get-internal-users[]

== 에러 응답
=== 인증 실패
operation::required-login-error[snippets='http-response']

=== 로그인한 유저를 찾을 수 없음
operation::login-user-notfound-error[snippets='http-response']

=== 잘못된 요청
operation::bad-request-error[snippets='http-response']


=== 알 수 없는 에러
operation::unknown-error[snippets='http-response']
