spring:
  profiles:
    default: local
  application:
    name: simpleboard-board-service
  config:
    import:
      - 'classpath:application-persistence.yml'
      - 'classpath:application-http.yml'
      - 'classpath:application-kafka-producer.yml'
      - 'classpath:application-mongodb.yml'
      - 'classpath:application-redis.yml'
  cloud:
    config:
      enabled: false
management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  metrics:
    tags:
      application: ${spring.application.name}
      profile: ${spring.profiles.active}
---
server:
  port: 8081
spring:
  config:
    activate:
      on-profile: local
---
spring:
  config:
    activate:
      on-profile: dev
    import:
      - optional:configserver:http://172.16.90.6
  cloud:
    config:
      enabled: true
      profile: dev
      name: mysql, redis, mongodb
