version: "3.9"
services:
  redis:
    image: redis:7.0-alpine
    ports:
      - "6389:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
