spring:
  profiles:
    default: local
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      # Encountered deprecated setting [javax.persistence.sharedCache.mode], use [jakarta.persistence.sharedCache.mode] instead
      jakarta.persistence.sharedCache.mode: ALL
  flyway:
    encoding: utf-8
    baseline-version: 0
    baseline-on-migrate: true
    enabled: false

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3308/users
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    show-sql: true
  flyway:
    enabled: true
  data:
    redis:
      host: localhost
      port: 6389
      connect-timeout: 3000
      timeout: 1000

oauth2:
  kakao:
    client-id: 36a710c0f0041dcbb3f68b717171c947
    redirect-uri:
      login: http://localhost:3000/login/kakao
      user-link: http://localhost:3000/mypage/kakao/link

token:
  access:
    expiration: 10s
    secret: jekmrsrhPKOwSUnR7m8WtcWv_K5SdKygftw3x99BrCs
  refresh:
    expiration: 1d
    secret: 8p1WxOIxZchtCRgQ0TeqYyV-0T86IR2rZhhVTwTtxLQ

micro-services:
  image-service-url: http://localhost:8082

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://192.168.29.15:3306/users
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    show-sql: true
  flyway:
    enabled: true
  data:
    redis:
      host: 192.168.29.17
      port: 6379
      connect-timeout: 3000
      timeout: 1000

oauth2:
  kakao:
    client-id: b623fc344a47932f1df4c840426bb5df
    redirect-uri:
      login: https://simpleforum.yellowsunn.com/login/kakao
      user-link: https://simpleforum.yellowsunn.com/mypage/kakao/link

token:
  access:
    expiration: 30m
    secret: ${access-token-secret}
  refresh:
    expiration: 1d
    secret: ${refresh-token-secret}

micro-services:
  image-service-url: http://dev-simpleforum-image-service-svc:8080
