spring:
  profiles:
    default: local
  config:
    import:
      - 'classpath:application-user-infra-persistence.yml'
      - 'classpath:application-user-core.yml'
      - 'classpath:application-redis.yml'
      - 'classpath:application-http.yml'
  cloud:
    config:
      enabled: false
---
spring:
  config:
    activate:
      on-profile: local
---
spring:
  config:
    activate:
      on-profile: dev
    import:
      - optional:configserver:http://172.16.90.6
  cloud:
    config:
      enabled: true
      profile: dev
      name: mysql, redis

