spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google-client-id}
            client-secret: ${google-client-secret}
            redirect-uri: '${micro-services.api-gateway-url}/{action}/oauth2/code/{registrationId}'
            scope:
              - email
              - profile
          naver:
            client-id: ${naver-client-id}
            client-secret: ${naver-client-secret}
            client-name: Naver
            redirect-uri: '${micro-services.api-gateway-url}/{action}/oauth2/code/{registrationId}'
            authorization-grant-type: authorization_code
            scope:
              - email
              - profile_image
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
---
spring:
  profiles:
    active: local

micro-services:
  api-gateway-url: http://localhost:8000
  front-end-url: http://localhost:3000
