name: frontend-service dev 배포 파이프라인
on:
  workflow_dispatch:
jobs:
  build-deploy:
    runs-on:
      - ubuntu-latest
    env:
      container-image: yellowsunn/simpleforum-frontend-service
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Get current time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: yyyyMMDDHHmmss
          utcOffset: "+09:00"
      - name: Get deploy version
        run: echo "deployment-version=SNAPSHOT-${{ steps.current-time.outputs.formattedTime }}" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: ./frontend-service/Dockerfile
          context: ./frontend-service
          build-args: ACTIVE_PROFILES=dev
          no-cache: true
          push: true
          tags: ${{ env.container-image }}:latest,${{ env.container-image }}:${{ env.deployment-version }}
      - name: Dispatch changing image tag action
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{owner}/{repo}/dispatches
          owner: yellowsunn
          repo: argocd-manifest
          event_type: change-image-tag
          client_payload: |
            {
              "requested-event-path": "${{ env.GITHUB_EVENT_PATH }}",
              "container-image": "${{ env.container-image }}",
              "deployment-version": "${{ env.deployment-version }}",
              "overlay-path": "manifest/simpleforum/frontend-service/overlays/dev"
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_HUB_PERSONAL_ACCESS_TOKEN }}
