name: image-service rest docs api 업데이트 파이프라인
on:
  workflow_dispatch:
jobs:
  build-deploy:
    runs-on:
      - ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Set git config
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Change imag tag
        run: |
          git merge main
          ./gradlew :image-service:asciidoctor
          ls -al
