name: image-service rest docs api 업데이트 파이프라인
on:
  workflow_dispatch:
jobs:
  build-deploy:
    runs-on:
      - ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Merge main -> gh-pages branch
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main
          target_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Update rest docs api document
        run: |
          ./gradlew :image-service:asciidoctor
          mv ./image-service/build/docs/asciidoc/index.html ./docs/image-service.html
          ls -al docs
      - name: commit api document
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "[github-action] update api document"
          git push
